/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingLeadRouteImport } from './routes/training-lead'
import { Route as TeamLeaderRouteImport } from './routes/team-leader'
import { Route as QualityLeaderRouteImport } from './routes/quality-leader'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'

const TrainingLeadRoute = TrainingLeadRouteImport.update({
  id: '/training-lead',
  path: '/training-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamLeaderRoute = TeamLeaderRouteImport.update({
  id: '/team-leader',
  path: '/team-leader',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityLeaderRoute = QualityLeaderRouteImport.update({
  id: '/quality-leader',
  path: '/quality-leader',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/quality-leader': typeof QualityLeaderRoute
  '/team-leader': typeof TeamLeaderRoute
  '/training-lead': typeof TrainingLeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/quality-leader': typeof QualityLeaderRoute
  '/team-leader': typeof TeamLeaderRoute
  '/training-lead': typeof TrainingLeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/quality-leader': typeof QualityLeaderRoute
  '/team-leader': typeof TeamLeaderRoute
  '/training-lead': typeof TrainingLeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/quality-leader'
    | '/team-leader'
    | '/training-lead'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agent' | '/quality-leader' | '/team-leader' | '/training-lead'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/quality-leader'
    | '/team-leader'
    | '/training-lead'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  QualityLeaderRoute: typeof QualityLeaderRoute
  TeamLeaderRoute: typeof TeamLeaderRoute
  TrainingLeadRoute: typeof TrainingLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training-lead': {
      id: '/training-lead'
      path: '/training-lead'
      fullPath: '/training-lead'
      preLoaderRoute: typeof TrainingLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-leader': {
      id: '/team-leader'
      path: '/team-leader'
      fullPath: '/team-leader'
      preLoaderRoute: typeof TeamLeaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality-leader': {
      id: '/quality-leader'
      path: '/quality-leader'
      fullPath: '/quality-leader'
      preLoaderRoute: typeof QualityLeaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  QualityLeaderRoute: QualityLeaderRoute,
  TeamLeaderRoute: TeamLeaderRoute,
  TrainingLeadRoute: TrainingLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
